### ISSUE TITLE
OutOfMemoryException When Building IDataSource for Training

### ISSUE THREAD

**Issue by FusionCarcass** [jdermody/brightwire#10]
When running the code below, I run into a 'System.OutOfMemoryException' in the dataTable.Add() method. This occurs whenever I add an additional FloatVector that puts the total number of bytes of features added over 2GB. For example, if the number of features for each sample is 7192, then I can add 74,648 samples to the IDataTableBuilder object. When I add the 74,649th item, I receive the above exception.

I thought that I could get around this by forcing my application to allow large objects; however, that did not fix the issue and I confirmed that my application can allocate objects that take up more than 2GB of RAM.

Is there something that can be done on your end?

```csharp
protected IDataSource BuildDataTable(Int32 start, Int32 stop, ValidationInput[] items, GraphFactory graph)
{
     var dataTable = BrightWireProvider.CreateDataTableBuilder();
     dataTable.AddColumn(ColumnType.Vector, "Data");
     dataTable.AddColumn(ColumnType.Vector, "Class", true);

     for (int i = start; i <= stop; i++)
     {
          //convert features to float[]
          Matrix32 m = items[i].Features;
          float[] data = new float[m.Columns];
          for (uint j = 0; j < m.Columns; j++)
          {
               data[j] = m[0, j];
          }

          //convet output to one-hot encoded float[]
          float[] output = new float[2];
          output[items[i].Index] = 1.0f;

          FloatVector vectorInput = new FloatVector { Data = data };
          FloatVector vectorOutput = new FloatVector { Data = output };

          dataTable.Add(vectorInput, vectorOutput);
     }

     return graph.CreateDataSource(dataTable.Build());
}
```

**Comment by jdermody** [comment]
I'll take a look at this. In the meantime, you're compiling explicitly for x64, right?

**Comment by FusionCarcass** [comment]
Thanks for the quick response. That works for me.
