### ISSUE TITLE
How can I save/load Vectoriser for DataTable

### ISSUE THREAD

**Issue by kevinlai9527** [jdermody/brightwire#11]
I'm using a data table with string (label column) as training set, and a vectoriser is used to translater result float vector and label.

What is the best way to save/load Vectoriser so I can reuse the network without training again?

Thank you very much.

**Comment by jdermody** [comment]
Hi

There currently isn't any way to save and load a IDataTableVectorisor, unfortunately.

I can see how that would be a useful feature.

It could be done along the lines of DataTableNormaliser/DataTableNormalisation that output a serialisable model that performs the actual mapping.

This isn't a huge piece of work and could be added to the next release of BW.

**Comment by jdermody** [comment]
Fixed in [2.0.4](https://github.com/jdermody/brightwire/releases/tag/2.0.4)
