### ISSUE TITLE
Determining column types in DataTable

### ISSUE THREAD

**Issue by trunda-o** [jdermody/brightwire#14]
Hi, I've encountered some strange behavior when loading data into a DataTable by 

var dataTable = new System.IO.StreamReader(dataFilePath).ParseCSV();

The method seems to be using the first 1024 rows from the file to determine data types for each column. In my data, the first 1200 or so rows contained only numbers smaller than 255 in one of the columns, so that column was treated as "byte". Later, however, numbers larger than 255 occurred, which caused a shift in the position of the underlaying stream. Basically all the remaining data was misread and become gibberish. (The problem becomes evident only after "dataTable.Split" is called.)

Is it possible to fix this simply by increasing the constant "DataTable.BLOCK_SIZE" to "int.MaxValue" or to some number larger than the number of rows in my data?

Thanks :)

**Comment by jdermody** [comment]
Hi, that's unfortunate! The DataTable.BLOCK_SIZE is used to determine how frequently the file position is indexed, so not the best place to fix this.

The best thing would be to add a parameter to the CSV parser that forces it to consider the entire table before working out the column sizes (or maybe do that by default).

This isn't a big piece of work and could be included in the next release.

Cheers,
Jack

**Comment by jdermody** [comment]
When parsing CSV the entire table is now parsed twice - the first time to verify the exact size of each column and the second to build the table to those types.
