### ISSUE TITLE
Request: Multi-labels classifier and Multivariate examples.

### ISSUE THREAD

**Issue by mctheaw** [jdermody/brightwire#15]
Hello Jack,

Are there any plan to add multi-labels classifier and multivariate examples?

Brightwire is a great project, keep up the good work.

Thank you

**Comment by jdermody** [comment]
Hi

Thanks, glad you like BW!

Good suggestion regarding additional classification samples. Did you have a publicly available data set in mind?

**Comment by mctheaw** [comment]
Thank you for the response :).

Predicting movie Genres from text or image cover would be a good example but I could find just a few white papers without data set.

So I think Mulan's datasets which are real world use cases would be great. You may pick any of them here.

http://mulan.sourceforge.net/datasets-mlc.html

Or some others below.

http://sci2s.ugr.es/keel/multilabel.php
https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/multilabel.html

Thank you :)

**Comment by jdermody** [comment]
I've added a multi label sample to brightwire/SampleCode/MultiLabel.cs that might help.

The first example trains a single neural network with six output values. The second builds six networks with each outputting a single value. Both give about the same result.

**Comment by mctheaw** [comment]
Wow that's awesome, thank you.
