### ISSUE TITLE
Is this irony???

### ISSUE THREAD

**Issue by ZdsAlpha** [jdermody/brightwire#20]
![brightwire](https://user-images.githubusercontent.com/13795176/42453644-cc876cd0-83a6-11e8-8ba8-dbb63ea3ed58.PNG)

**Comment by jdermody** [comment]
Yes, I agree that this is not ideal. Bright Wire actually only supports .net 4.6 and above but is labelled as .Net4 to distinguish it from the .net standard release (.net 4.6.1 or better).
