### ISSUE TITLE
1D convolutional filters, filters with different strides

### ISSUE THREAD

**Issue by trunda-o** [jdermody/brightwire#25]
Hi,

is there a way to use convolutional layer on 1D inputs (like a time series)? I can't make it work as it would require the "stride" parameter to work differently in width-dimension and height-dimension.
For example: suppose the input has dimension (100 x 1), I use several filters with size (10, 1), zero padding and stride (1, 0). Currently the "stride" is always the same in both dimensions.

I think that allowing different stride values in different dimensions can be useful for 2D convolutions as well. For example I might want the filter to move 2 tiles to the right and 1 tile down in every "iteration" when working with pictures.

Thanks.

**Comment by jdermody** [comment]
Agree.

**Comment by jdermody** [comment]
Implemented in 2.1.1
