### ISSUE TITLE
Input vector and output vector index in RowData

### ISSUE THREAD

**Issue by cacerzard** [jdermody/brightwire#35]
Thanks a lot for your contribution!
I am trying to use LSTM to predict weather information and referrenc to your sample code "StockData". Now I have a question about the index of taget vector in rows. I think it should be "i + LAST_X_DAYS" because the index of last vector in input matrix in rows is "i + LAST_X_DAYS - 1".

const int LAST_X_DAYS = 14;
for (var i = 0; i < rows.Count - LAST_X_DAYS - 1; i++) {
  var inputVector = new List<FloatVector>();
  for (var j = 0; j < LAST_X_DAYS; j++)
    inputVector.Add(FloatVector.Create(rows[i + j]));
  var input = FloatMatrix.Create(inputVector.ToArray());
  var target = FloatVector.Create(rows[i + LAST_X_DAYS+1]);
  builder.Add(input, target);
}

**Comment by jdermody** [comment]
Agree! Thank you for pointing it out.
