### ISSUE TITLE
Streaming data sources?

### ISSUE THREAD

**Issue by dje-dev** [jdermody/brightwire#40]
Thank you for a well designed library that looks very promising!

I have a large data set that cannot possible be held in memory, and want to train by streaming in window of data (vectors of floats). Is there example code which works with such large data sets, or a hint about what classes could be used to accomplish this?

**Comment by jdermody** [comment]
Yes, this is a problem with the standard data table adaptors - they read the entire table into memory.

The easiest place to start would be to create a new data table adaptor that inherits from _DataTableAdapterBase_ and that reads from a file based data table without first loading it into memory.

Alternatively you could create a new class entirely that implements _IDataSource_.

**Comment by jdermody** [comment]
Data table adaptors no longer read entire table into memory as of version 3.0.0-beta
