### ISSUE TITLE
Multiple targets

### ISSUE THREAD

**Issue by PatriceDargenton** [jdermody/brightwire#45]
Hi, how is it possible to have multiple targets? Independent targets or dependent targets, for example 2 independent XORs, but in other cases the outputs may be dependent. I tried this, but I saw that it is not possible to have multiple targets:

            var builder = context.BuildTable();
            builder.AddColumn(BrightDataType.Float, "X1");
            builder.AddColumn(BrightDataType.Float, "X2");
            builder.AddColumn(BrightDataType.Float, "Y1");
            builder.AddColumn(BrightDataType.Float, "Y2");
            builder.AddColumn(BrightDataType.Float, "XOR1").SetTarget(true);
            builder.AddColumn(BrightDataType.Float, "XOR2").SetTarget(true);

            builder.AddRow(1.0f, 0.0f, 1.0f, 0.0f, 1.0f, 1.0f); //1 0 1 0 : 1 1
            builder.AddRow(1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f); //1 0 0 0 : 1 0
            builder.AddRow(1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f); //1 0 0 1 : 1 1
            builder.AddRow(1.0f, 0.0f, 1.0f, 1.0f, 1.0f, 0.0f); //1 0 1 1 : 1 0
            builder.AddRow(0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f); //0 0 1 0 : 0 1
            builder.AddRow(0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f); //0 0 0 0 : 0 0
            builder.AddRow(0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f); //0 0 0 1 : 0 1
            builder.AddRow(0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f); //0 0 1 1 : 0 0
            builder.AddRow(0.0f, 1.0f, 1.0f, 0.0f, 1.0f, 1.0f); //0 1 1 0 : 1 1
            builder.AddRow(0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f); //0 1 0 0 : 1 0
            builder.AddRow(0.0f, 1.0f, 0.0f, 1.0f, 1.0f, 1.0f); //0 1 0 1 : 1 1
            builder.AddRow(0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f); //0 1 1 1 : 1 0
            builder.AddRow(1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 1.0f); //1 1 1 0 : 0 1
            builder.AddRow(1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f); //1 1 0 0 : 0 0
            builder.AddRow(1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 1.0f); //1 1 0 1 : 0 1
            builder.AddRow(1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f); //1 1 1 1 : 0 0

            return builder.BuildRowOriented();

because of this condition:

BrightWire.Net4: only one target:

        IsTargetColumn = columnInfo.ColumnIndex == classColumnIndex

BrightWire (,net core): only one target too:

        public static uint? GetTargetColumn(this IDataTable table)
        {
            var metaData = table.AllColumnsMetaData();
            for (uint i = 0; i < table.ColumnCount; i++) {
                if (metaData[i].IsTarget())
                    return i;
            }
            return null;
        }

**Comment by jdermody** [comment]
Yes, only one target column is supported but that target column can be a vector (of size 2), or matrix, tensor etc.

So you could do what you want by creating a data table with two vector columns - one with an input vector (of size 4) and the other with a target vector of size 2 and putting your values into the vectors rather than the tables.

**Comment by PatriceDargenton** [comment]
Thanks you very much, it works fine with both versions, here is an example for ,net core version:

            var builder = context.BuildTable();
            builder.AddColumn(BrightDataType.Float, "X1");
            builder.AddColumn(BrightDataType.Float, "X2");
            builder.AddColumn(BrightDataType.Float, "Y1");
            builder.AddColumn(BrightDataType.Float, "Y2");

            builder.AddColumn(BrightDataType.Vector, "XOR").SetTarget(true);
            builder.AddRow(1.0f, 0.0f, 1.0f, 0.0f, context.CreateVector(1.0f, 1.0f)); // 1 0 1 0 : 1 1
            builder.AddRow(1.0f, 0.0f, 0.0f, 0.0f, context.CreateVector(1.0f, 0.0f)); // 1 0 0 0 : 1 0
            builder.AddRow(1.0f, 0.0f, 0.0f, 1.0f, context.CreateVector(1.0f, 1.0f)); // 1 0 0 1 : 1 1
            builder.AddRow(1.0f, 0.0f, 1.0f, 1.0f, context.CreateVector(1.0f, 0.0f)); // 1 0 1 1 : 1 0
            builder.AddRow(0.0f, 0.0f, 1.0f, 0.0f, context.CreateVector(0.0f, 1.0f)); // 0 0 1 0 : 0 1
            builder.AddRow(0.0f, 0.0f, 0.0f, 0.0f, context.CreateVector(0.0f, 0.0f)); // 0 0 0 0 : 0 0
            builder.AddRow(0.0f, 0.0f, 0.0f, 1.0f, context.CreateVector(0.0f, 1.0f)); // 0 0 0 1 : 0 1
            builder.AddRow(0.0f, 0.0f, 1.0f, 1.0f, context.CreateVector(0.0f, 0.0f)); // 0 0 1 1 : 0 0
            builder.AddRow(1.0f, 1.0f, 1.0f, 0.0f, context.CreateVector(1.0f, 1.0f)); // 0 1 1 0 : 1 1
            builder.AddRow(1.0f, 1.0f, 0.0f, 0.0f, context.CreateVector(1.0f, 0.0f)); // 0 1 0 0 : 1 0
            builder.AddRow(1.0f, 1.0f, 0.0f, 1.0f, context.CreateVector(1.0f, 1.0f)); // 0 1 0 1 : 1 1
            builder.AddRow(1.0f, 1.0f, 1.0f, 1.0f, context.CreateVector(1.0f, 0.0f)); // 0 1 1 1 : 1 0
            builder.AddRow(0.0f, 1.0f, 1.0f, 0.0f, context.CreateVector(0.0f, 1.0f)); // 1 1 1 0 : 0 1
            builder.AddRow(0.0f, 1.0f, 0.0f, 0.0f, context.CreateVector(0.0f, 0.0f)); // 1 1 0 0 : 0 0
            builder.AddRow(0.0f, 1.0f, 0.0f, 1.0f, context.CreateVector(0.0f, 1.0f)); // 1 1 0 1 : 0 1
            builder.AddRow(0.0f, 1.0f, 1.0f, 1.0f, context.CreateVector(0.0f, 0.0f)); // 1 1 1 1 : 0 0

            return builder.BuildRowOriented();
