### ISSUE TITLE
Disable user notifications

### ISSUE THREAD

**Issue by PatriceDargenton** [jdermody/brightwire#46]
Hi, disabling user notifications works fine in the main repository:
using var context = new BrightDataContext(RandomSeed);
context.UserNotifications = null; // Disable user notifications

But how can we disable notifications in a separate project using the NuGet package?
using var context = new BrightDataContext(RandomSeed);
context.UserNotifications = null;
CS1061: 'BrightDataContext' does not contain a definition for 'UserNotifications' and no extension method 'UserNotifications' accepting a first argument of type 'BrightDataContext' could be found (are you missing a using directive or an assembly reference?)

**Comment by jdermody** [comment]
Updated in 3.0.2 nuget package
