### ISSUE TITLE
ValueTuple version isssue

### ISSUE THREAD

**Issue by MMike0782** [jdermody/brightwire#5]
Hi I just downloaded ver 4.6 and tried to run the iris res classification example and i'm getting a versioning issue with the ValueTuple at version 4.0.1.1 being at a higher ver than 4.0.1.0 .
I'm using VS2015 and framework 4.6.1. Any pointers would be most helpful

regards

Mike

**Comment by jdermody** [comment]
Hmm. Did you try consolidating your solution references to the same version of the ValueTuple assembly?

**Comment by jdermody** [comment]
Also, when building for the first time make sure you restore the nuget packages (Right click on solution, "Manage NuGet Packages for Solution", then click Restore).
