### ISSUE TITLE
Save and load Markov models

### ISSUE THREAD

**Issue by MaddalenaTech** [jdermody/brightwire#7]
I'm playing with this example ( it's wonderful ) but I don't find a way to save and load the model properly

https://github.com/jdermody/brightwire/blob/master/SampleCode/MarkovChains.cs

i can save and load the generated model (MarkovModel3<string>) via Protobuf but when it's loaded there is no way to put those data into the trainer so at the next Build whatever i saved and loaded is overriden.

Short code:

```
static IMarkovModelTrainer3<string> trainer = BrightWireProvider.CreateMarkovTrainer3<string();
static MarkovModel3<string> markovModel;

            if(File.Exists("model.bin"))
                using (var file = File.Open("model.bin", FileMode.OpenOrCreate))
                {
                    markovModel = ProtoBuf.Serializer.Deserialize<MarkovModel3<string>>(file);
                    trainer.Add(markovModel.);
                }

                markovModel = trainer.Build();
                var model = markovModel?.AsDictionary;
```

**Comment by jdermody** [comment]
Fixed in [2.0.3](https://github.com/jdermody/brightwire/releases/tag/2.0.3)
